//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X_Bot_First_Class.JumpStart {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("X_Bot_First_Class.JumpStart.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;body&gt;
        ///  &lt;p&gt;Hello, {{0}},&lt;/p&gt;
        ///    &lt;br /&gt;
        ///  &lt;p&gt;We regret to inform you that you were not selected for the {{1}} position. Although the position has been filled, we recommend you take a look at the following 3 job positions which require similar skills.&lt;/p&gt;
        ///    &lt;br /&gt;
        ///  &lt;p&gt;
        ///    &lt;ol&gt;
        ///      &lt;li&gt;
        ///        &lt;a href=&quot;#&quot;&gt;{{2}}&lt;/a&gt;
        ///      &lt;/li&gt;
        ///      &lt;li&gt;
        ///        &lt;a href=&quot;#&quot;&gt;{{3}}&lt;/a&gt;
        ///      &lt;/li&gt;
        ///      &lt;li&gt;
        ///        &lt;a href=&quot;#&quot;&gt;{{4}}&lt;/a&gt;
        ///      &lt;/li&gt;
        ///    &lt;/ol&gt;
        ///  &lt;/p&gt;
        ///&lt;/body&gt;
        ///&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rejectionEmailTemplate {
            get {
                return ResourceManager.GetString("rejectionEmailTemplate", resourceCulture);
            }
        }
    }
}
