//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace X_Bot_First_Class {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("X_Bot_First_Class.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;body&gt;
        ///    &lt;p&gt;Take care! Goodbye.&lt;/p&gt;
        ///    &lt;p&gt;
        ///        &lt;div&gt;Rachael&lt;/div&gt;
        ///        &lt;div&gt;Artificial Executive Assistant&lt;/div&gt;
        ///    &lt;/p&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string goodbyeEmailTemplate {
            get {
                return ResourceManager.GetString("goodbyeEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome, {0}! How can I help you?.
        /// </summary>
        internal static string mgsWelcomeWithName {
            get {
                return ResourceManager.GetString("mgsWelcomeWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What name should I call you by?.
        /// </summary>
        internal static string msgGetName {
            get {
                return ResourceManager.GetString("msgGetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goodbye!.
        /// </summary>
        internal static string msgGoodbye {
            get {
                return ResourceManager.GetString("msgGoodbye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry. I didn&apos;t catch that..
        /// </summary>
        internal static string msgIDidntCatchThat {
            get {
                return ResourceManager.GetString("msgIDidntCatchThat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK. From now on I will call you {0}..
        /// </summary>
        internal static string msgIWillCallYou {
            get {
                return ResourceManager.GetString("msgIWillCallYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello. My name is Rachael. With whom do I have the pleasure of chatting with?.
        /// </summary>
        internal static string msgWelcome {
            get {
                return ResourceManager.GetString("msgWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back, {0}! How can I help you?.
        /// </summary>
        internal static string msgWelcomeBack {
            get {
                return ResourceManager.GetString("msgWelcomeBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK. What should I call you?.
        /// </summary>
        internal static string msgWhatShouldICallYou {
            get {
                return ResourceManager.GetString("msgWhatShouldICallYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;body&gt;
        ///    &lt;p&gt;{0},&lt;/p&gt;
        ///    &lt;p&gt;This is Rachael from Express. I am sorry but you were not selected for the {1} position. Although the position has been filled, we recommend you take a look at the following {2} job positions which require similar skills.&lt;/p&gt;
        ///    &lt;p&gt;
        ///        &lt;ol&gt;
        ///            {3}
        ///        &lt;/ol&gt;
        ///    &lt;/p&gt;
        ///    &lt;p&gt;If you would like to apply for a position, reply to this email with the job number from the above list and I will submit your application.&lt;/p&gt;
        ///    &lt;p&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rejectionEmailTemplate {
            get {
                return ResourceManager.GetString("rejectionEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;body&gt;
        ///    &lt;p&gt;{1}&lt;/p&gt;
        ///    &lt;p&gt;
        ///        &lt;div&gt;Rachael&lt;/div&gt;
        ///        &lt;div&gt;Artificial Executive Assistant&lt;/div&gt;
        ///    &lt;/p&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string suggestionApplyEmailTemplate {
            get {
                return ResourceManager.GetString("suggestionApplyEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;body&gt;
        ///    &lt;p&gt;You are most welcome.&lt;/p&gt;
        ///    &lt;p&gt;
        ///        &lt;div&gt;Rachael&lt;/div&gt;
        ///        &lt;div&gt;Artificial Executive Assistant&lt;/div&gt;
        ///    &lt;/p&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string thankYouEmailTemplate {
            get {
                return ResourceManager.GetString("thankYouEmailTemplate", resourceCulture);
            }
        }
    }
}
